### ISSUE TITLE
Poly1305 key misuse - attackers can forge authenticated tokens

### ISSUE THREAD

**Issue by brycx** [scottbrady91/IdentityModel#3]
In extension of #2, the current code in Branca allows attackers to forge authenticated tokens, if a user uses any given key more than once ([see NaCl](https://nacl.cr.yp.to/onetimeauth.html)).

The issue lies in the use of the same key for both encryption and authentication of the token.

```c#
var keyMaterial = new KeyParameter(key);
var parameters = new ParametersWithIV(keyMaterial, nonce);

var engine = new XChaChaEngine();
engine.Init(true, parameters);
```

and

```c#
var poly = new Poly1305();
poly.Init(keyMaterial);
```

This will automatically be fixed, if the Branca implementation adheres to the specification.

**Comment by scottbrady91** [comment]
Addressed by moving to libsodium implementation
